### ISSUE TITLE
Can we choose platform like HOSE only?

### ISSUE THREAD

**Issue by hoangtn1304** [vincetran96/Scrape-Finance-Data-v2#3]
Is there any way so we can download only data from HOSE or another platform? for now it downloads everything and take several days to finish.

**Comment by vietzerg** [comment]
As mentioned in the `README`, this scraper was originally created with the top-down approach in mind to download as much data as possible, which means it goes from industry and business types to individual companies. This method was intended for a machine learning project of mine. Thus, for now, it is not possible to download data from a specific exchange. However, if I remember correctly, Vietstock has an API for exchanges, given that [this page](https://finance.vietstock.vn/doanh-nghiep-a-z?page=1) has a filter for exchanges.

If you are interested in getting data specific for an exchange, there are several options:

1. Create a pull request
2. Fork this project and modify it yourself
3. Leave this issue open and if I have the time, I will look into this (no guarantee though)

Thanks for raising the issue!

**Comment by hoangtn1304** [comment]
thanks, I found out how, it's in the constants config
