### ISSUE TITLE
New API security measure from Vietstock

### ISSUE THREAD

**Issue by vincetran96** [vincetran96/Scrape-Finance-Data-v2#8]
Tasks:
- [x] Change constants to workaround this
- [x] Update README

Vietstock has implemented `__RequestVerificationToken` to prevent cross-site request forgery attacks. Unless that issue is addressed, this application cannot download financials anymore.

More about `__RequestVerificationToken`:

- [https://stackoverflow.com/questions/14051456/whats-the-use-of-the-requestverificationtoken](https://stackoverflow.com/questions/14051456/whats-the-use-of-the-requestverificationtoken)
- [https://stackoverflow.com/questions/44783702/what-is-the-use-of-html-antiforgerytoken](https://stackoverflow.com/questions/44783702/what-is-the-use-of-html-antiforgerytoken)

**Comment by vincetran96** [comment]
A `RequestVerificationToken` for the cookie and the POST request can be obtained from Vietstock by the user himself, but there is no information on how long the token is valid for.

**Comment by truongphanduykhanh** [comment]
Thanks for your work!

**Comment by vincetran96** [comment]
It looks like the token is only valid for one day.
